### ISSUE TITLE
Prepopulate the mailbox with a welcome email

### ISSUE THREAD

**Issue by daurnimator** [hashbang/provisor#3]
17:28:57 <+daurn> prepopulate the mailbox with a welcome email or something
17:29:20 <+daurn> mutt usage instructions would be a great first email ;)
17:29:20 <~lrvick> daurn: Yeah I was wanting to do that, but I'll proabbly have to send them a realil fro support
17:29:23 <~lrvick> which they can reply to if they want
17:29:26 <~lrvick> submit an isue to remind me

**Comment by AlissaSquared** [comment]
Give me what file to edit to do this and I'll get to working on it.

**Comment by geoffmcc** [comment]
I was just messing around with this. More of a hack really. Probably a better way to do it (maybe actually send new users email on account creation???)

It seems that mutt will accept anything as mail when it is in the directory. The only thing, if it does not contain the date headers and the like, the date will appear as Jan 1.

I created a msg.welcome fle and placed into Mail/new and then checked it out in mutt.
I adjusted things like from to be noreply@hashbang.sh and to was newuser@hashbang.sh

Anyways, main drawbacks here are the username set to newuser and as I said before, if no date given, will display as Jan 1

Attached are screenshots. From just shows as Welcome as I failed to add the @hashbang.sh, I also set reply to noreply@hashbang.sh

It may be possible make a template and then autoscript in the correct info for user and date

Here are some screencaps

http://imgur.com/a/YA6bu

**Comment by AlissaSquared** [comment]
That was my plan already. From what I can see, it looks like [provisor](https://github.com/hashbang/provisor) is written in Python. I might not be a god at the language, but a few hours of buttonmashing can get me a good substitution script that can automatically generate a welcome file. I'm just not entirely sure how the scripts work, but I can look into that later if needed.

**Comment by AlissaSquared** [comment]
Actually, what I'll be doing now, is sending an email to my inbox (now that's working \o/), and just modifying things from there. Seems easier.

**Comment by geoffmcc** [comment]
Yeah, thats what i did. 

But the names and dates will need to change

**Comment by AlissaSquared** [comment]
http://pae.st/y#WEB-PUBLIC is what I currently have.
If someone could take a look at that and tell me why Mutt doesn't want to display it, that would be great :D

**Comment by dpflug** [comment]
I don't think date info is supposed to be appended to the From:. That's my
first guess.

**Comment by AlissaSquared** [comment]
Yeah, I fixed that up. Later I'll look into how the core of provisor works and see if I can add in the automation of sending the email.

**Comment by geoffmcc** [comment]
im playing around with this to suite our needs. It works if you manually enter the to and from. I am just trying to figure out how to script that info in from provisor, but it is a bit out of my scope. I'm really just learning python, but I am usually good at reading code and modifying to be what I need.

Im sure I will get there, but I bet Alissa could get there faster.

https://gist.github.com/geoffmcc/3122380f93a8f0cea209#file-sendmail-py

**Comment by AlissaSquared** [comment]
As of right now I'm working on it with a different repository. Can't look at it as patents get upset when I'm coming our eating with a laptop, so gave fun until then. 

-----Original Message-----

**Comment by AlissaSquared** [comment]
As said on IRC, we're trying to use a file-moving-and-.format() sequence and also move this to hashbang.sh instead of provisor.
I have the logic down,
```lua
local f = io.open( "your/new/file" )
for line in io:lines( "new.welcome" ) do
 f:write( line:gsub( "{(.-)}", data ) .. "\r\n" )
end
f:close()
```
The line:gsub can be replaced with format in Python, but that's the basic logic :)
Anyways, closing and re-opening on hashbang.sh
