### ISSUE TITLE
validate_pubkey: Removal of quotes etc

### ISSUE THREAD

**Issue by reynir** [hashbang/provisor#33]
I noticed that in `validate_pubkey` quotes are removed. Why is this? It's incorrect if the key contains options, e.g.:

```
command="echo 'Hello, there!'" ssh-rsa AAAAB3NzaC1yc...
```

https://github.com/hashbang/provisor/blob/09992b78dbe959323b00bd59625234ab9825a0a4/provisor/utils.py#L33

**Comment by KellerFuchs** [comment]
@reynir Yes, the parser in `validate_pubkey` is bad, but I don't think this should be a separate bug from #32 (because the replacement is unnecessary but also safe in the case where there are no key options).

If you agree, please close the bug  :)
