### ISSUE TITLE
Change permissions to allow nginx to serve files.

### ISSUE THREAD

**Issue by dpflug** [hashbang/provisor#7]
We need to change the homedir to o+x (**1) and ~/Public (and everything below it) to o+rx (**5).

We may also want to chgrp www-data ~/Public and set it set_gid, but that's not necessary. Without it, users will have to make sure any files they put in ~/Public have the proper permissions. With it, we avoid having to answer that question every time a new person tries to host something. ;)

Although, having a command on the bot to link them to docs for that could work, too.

**Comment by KellerFuchs** [comment]
That's not an issue for `provisor`.
It should probably go in `shell-etc`, except that this is not how we plan to do HTTP(S) for our users.
