### ISSUE TITLE
Implement captcha system

### ISSUE THREAD

**Issue by lrvick** [hashbang/provisor#8]
User makes POST request to create an account.

Instead of processing immediately, server stores request and responds with a question from a private Q/A database and a session token:

```
{ message: "Answer captcha question", question:"What color is a platypus?",sessionToken:"3no87nf9863gb796dfg78ds5f"}
```

Client responds with answer and session token.
```
{ sessionToken:"3no87nf9863gb796dfg78ds5f", answer:"purple"}
```
Actual account creation is then run from cache:
```
{ message: "Account Created"}
```

**Comment by hogmoru** [comment]
OK, I felt bad for posting a new issue + pull request without diligently checking existing issues, so here I am commenting on old ones, but hey it's still open, right?
So here is a suggestion: [TextCaptcha](http://textcaptcha.com/) offers an API for this.
- User makes POST request to create account
- Server invokes TextCaptcha API (maybe once every 5s as in the examples, be nice with the guy), gets a challenge and md5 for valid lowercase answer(s)
- Server sends challenge to user
- User sends response
- Server md5hashes the response, checks against valid answers, yadda yadda.

Reasons not to use this:
- you might want not to depend on external service.
- you want to be full open source, no secrets, even the captchas source must be open, so it must not be a giant list of fixed Q/A, but rather a list of challenges that can only be solved by a human (but I don't suppose that exists, hehe).

But it seems to match your use case, and easy to plug in, so it can be useful to try this for a time and see if it's beneficial, and then you choose to invest more time to roll your own.

**Comment by lrvick** [comment]
Support for this is now being tracked here: https://github.com/hashbang/hashbang/pull/11
