### ISSUE TITLE
Obscure error message when trying to create account with existing username.

### ISSUE THREAD

**Issue by Aagat** [hashbang/provisor#9]
When trying to create new user with existing username, the installation script doesn't display proper error message.

**Comment by necrophcodr** [comment]
This is a true, and problematic issue. Most likely, the script should, at least, attempt to print any error messages sent by the server.

**Comment by KellerFuchs** [comment]
Solved a while ago:
```
 Creating your account...  Account creation failed: User already exists
 
 If you think this is a bug, please report it to 
 -> https://github.com/hashbang/hashbang.sh/issues/
 
 The installer will not continue from here...
```
